// CREATE
export const CREATE_STEP_REQUEST = "CREATE_STEP_REQUEST";
export const CREATE_STEP_SUCCESS = "CREATE_STEP_SUCCESS";
export const CREATE_STEP_FAIL = "CREATE_STEP_FAIL";

// GET / LIST
export const GET_STEPS_REQUEST = "GET_STEPS_REQUEST";
export const GET_STEPS_SUCCESS = "GET_STEPS_SUCCESS";
export const GET_STEPS_FAIL = "GET_STEPS_FAIL";

// UPDATE
export const UPDATE_STEP_REQUEST = "UPDATE_STEP_REQUEST";
export const UPDATE_STEP_SUCCESS = "UPDATE_STEP_SUCCESS";
export const UPDATE_STEP_FAIL = "UPDATE_STEP_FAIL";

// DELETE
export const DELETE_STEP_REQUEST = "DELETE_STEP_REQUEST";
export const DELETE_STEP_SUCCESS = "DELETE_STEP_SUCCESS";
export const DELETE_STEP_FAIL = "DELETE_STEP_FAIL";