export const CREATE_MACHINE_REQUEST = "CREATE_MACHINE_REQUEST";
export const CREATE_MACHINE_SUCCESS = "CREATE_MACHINE_SUCCESS";
export const CREATE_MACHINE_FAIL = "CREATE_MACHINE_FAIL";



export const GET_MACHINE_REQUEST = "GET_MACHINE_REQUEST";
export const GET_MACHINE_SUCCESS = "GET_MACHINE_SUCCESS";
export const GET_MACHINE_FAIL = "GET_MACHINE_FAIL";



export const GET_MACHINES_REQUEST = "GET_MACHINES_REQUEST";
export const GET_MACHINES_SUCCESS = "GET_MACHINES_SUCCESS";
export const GET_MACHINES_FAIL = "GET_MACHINES_FAIL";



export const UPDATE_MACHINE_REQUEST = "UPDATE_MACHINE_REQUEST";
export const UPDATE_MACHINE_SUCCESS = "UPDATE_MACHINE_SUCCESS";
export const UPDATE_MACHINE_FAIL = "UPDATE_MACHINE_FAIL";

export const DELETE_MACHINE_REQUEST = "DELETE_MACHINE_REQUEST";
export const DELETE_MACHINE_SUCCESS = "DELETE_MACHINE_SUCCESS";
export const DELETE_MACHINE_FAIL = "DELETE_MACHINE_FAIL";