export const CREATE_OPERATOR_REQUEST = "CREATE_OPERATOR_REQUEST";
export const CREATE_OPERATOR_SUCCESS = "CREATE_OPERATOR_SUCCESS";
export const CREATE_OPERATOR_FAIL = "CREATE_OPERATOR_FAIL";

export const FETCH_OPERATORS_REQUEST = "FETCH_OPERATORS_REQUEST";
export const FETCH_OPERATORS_SUCCESS = "FETCH_OPERATORS_SUCCESS";
export const FETCH_OPERATORS_FAIL = "FETCH_OPERATORS_FAIL";

export const UPDATE_OPERATOR_REQUEST = "UPDATE_OPERATOR_REQUEST";
export const UPDATE_OPERATOR_SUCCESS = "UPDATE_OPERATOR_SUCCESS";
export const UPDATE_OPERATOR_FAIL = "UPDATE_OPERATOR_FAIL";

export const DELETE_OPERATOR_REQUEST = "DELETE_OPERATOR_REQUEST";
export const DELETE_OPERATOR_SUCCESS = "DELETE_OPERATOR_SUCCESS";
export const DELETE_OPERATOR_FAIL = "DELETE_OPERATOR_FAIL";