export const CREATE_MATERIAL_REQUEST = "CREATE_MATERIAL_REQUEST";
export const CREATE_MATERIAL_SUCCESS = "CREATE_MATERIAL_SUCCESS";
export const CREATE_MATERIAL_FAIL = "CREATE_MATERIAL_FAIL";

export const GET_MATERIALS_REQUEST = "GET_MATERIALS_REQUEST";
export const GET_MATERIALS_SUCCESS = "GET_MATERIALS_SUCCESS";
export const GET_MATERIALS_FAIL = "GET_MATERIALS_FAIL";

export const UPDATE_MATERIAL_REQUEST = "UPDATE_MATERIAL_REQUEST";
export const UPDATE_MATERIAL_SUCCESS = "UPDATE_MATERIAL_SUCCESS";
export const UPDATE_MATERIAL_FAIL = "UPDATE_MATERIAL_FAIL";

export const DELETE_MATERIAL_REQUEST = "DELETE_MATERIAL_REQUEST";
export const DELETE_MATERIAL_SUCCESS = "DELETE_MATERIAL_SUCCESS";
export const DELETE_MATERIAL_FAIL = "DELETE_MATERIAL_FAIL";