export const ADD_PRODUCT_CATEGORY_REQUEST = "ADD_PRODUCT_CATEGORY_REQUEST";
export const ADD_PRODUCT_CATEGORY_SUCCESS = "ADD_PRODUCT_CATEGORY_SUCCESS";
export const ADD_PRODUCT_CATEGORY_FAIL = "ADD_PRODUCT_CATEGORY_FAIL";

export const GET_PRODUCT_CATEGORIES_REQUEST = "GET_PRODUCT_CATEGORIES_REQUEST";
export const GET_PRODUCT_CATEGORIES_SUCCESS = "GET_PRODUCT_CATEGORIES_SUCCESS";
export const GET_PRODUCT_CATEGORIES_FAIL = "GET_PRODUCT_CATEGORIES_FAIL";




export const GET_ALL_PRODUCT_TYPES_WITH_PRODUCTS_REQUEST = "GET_ALL_PRODUCT_TYPES_WITH_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCT_TYPES_WITH_PRODUCTS_SUCCESS = "GET_ALL_PRODUCT_TYPES_WITH_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCT_TYPES_WITH_PRODUCTS_FAIL = "GET_ALL_PRODUCT_TYPES_WITH_PRODUCTS_FAIL";




export const UPDATE_PRODUCT_CATEGORY_REQUEST = "UPDATE_PRODUCT_CATEGORY_REQUEST";
export const UPDATE_PRODUCT_CATEGORY_SUCCESS = "UPDATE_PRODUCT_CATEGORY_SUCCESS";
export const UPDATE_PRODUCT_CATEGORY_FAIL = "UPDATE_PRODUCT_CATEGORY_FAIL";

export const DELETE_PRODUCT_CATEGORY_REQUEST = "DELETE_PRODUCT_CATEGORY_REQUEST";
export const DELETE_PRODUCT_CATEGORY_SUCCESS = "DELETE_PRODUCT_CATEGORY_SUCCESS";
export const DELETE_PRODUCT_CATEGORY_FAIL = "DELETE_PRODUCT_CATEGORY_FAIL";