// ManagerConstants.ts
export const MANAGER_CREATE_REQUEST = "MANAGER_CREATE_REQUEST";
export const MANAGER_CREATE_SUCCESS = "MANAGER_CREATE_SUCCESS";
export const MANAGER_CREATE_FAIL = "MANAGER_CREATE_FAIL";

export const MANAGER_GET_ALL_REQUEST = "MANAGER_GET_ALL_REQUEST";
export const MANAGER_GET_ALL_SUCCESS = "MANAGER_GET_ALL_SUCCESS";
export const MANAGER_GET_ALL_FAIL = "MANAGER_GET_ALL_FAIL";

export const MANAGER_UPDATE_REQUEST = "MANAGER_UPDATE_REQUEST";
export const MANAGER_UPDATE_SUCCESS = "MANAGER_UPDATE_SUCCESS";
export const MANAGER_UPDATE_FAIL = "MANAGER_UPDATE_FAIL";

export const MANAGER_DELETE_REQUEST = "MANAGER_DELETE_REQUEST";
export const MANAGER_DELETE_SUCCESS = "MANAGER_DELETE_SUCCESS";
export const MANAGER_DELETE_FAIL = "MANAGER_DELETE_FAIL";