// Create Branch
export const BRANCH_CREATE_REQUEST = "BRANCH_CREATE_REQUEST";
export const BRANCH_CREATE_SUCCESS = "BRANCH_CREATE_SUCCESS";
export const BRANCH_CREATE_FAIL = "BRANCH_CREATE_FAIL";

// Get All Branches
export const BRANCH_LIST_REQUEST = "BRANCH_LIST_REQUEST";
export const BRANCH_LIST_SUCCESS = "BRANCH_LIST_SUCCESS";
export const BRANCH_LIST_FAIL = "BRANCH_LIST_FAIL";

// Delete Branch
export const BRANCH_DELETE_REQUEST = "BRANCH_DELETE_REQUEST";
export const BRANCH_DELETE_SUCCESS = "BRANCH_DELETE_SUCCESS";
export const BRANCH_DELETE_FAIL = "BRANCH_DELETE_FAIL";

// Update Branch
export const BRANCH_UPDATE_REQUEST = "BRANCH_UPDATE_REQUEST";
export const BRANCH_UPDATE_SUCCESS = "BRANCH_UPDATE_SUCCESS";
export const BRANCH_UPDATE_FAIL = "BRANCH_UPDATE_FAIL";