export const ADD_MACHINE_TYPE_REQUEST = "ADD_MACHINE_TYPE_REQUEST";
export const ADD_MACHINE_TYPE_SUCCESS = "ADD_MACHINE_TYPE_SUCCESS";
export const ADD_MACHINE_TYPE_FAIL = "ADD_MACHINE_TYPE_FAIL";

export const GET_MACHINE_TYPES_REQUEST = "GET_MACHINE_TYPES_REQUEST";
export const GET_MACHINE_TYPES_SUCCESS = "GET_MACHINE_TYPES_SUCCESS";
export const GET_MACHINE_TYPES_FAIL = "GET_MACHINE_TYPES_FAIL";

export const MACHINE_TYPE_REQUEST = "MACHINE_TYPE_REQUEST";
export const MACHINE_TYPE_SUCCESS = "MACHINE_TYPE_SUCCESS";
export const MACHINE_TYPE_FAIL = "MACHINE_TYPE_FAIL";




export const UPDATE_MACHINE_TYPE_REQUEST = 'UPDATE_MACHINE_TYPE_REQUEST';
export const UPDATE_MACHINE_TYPE_SUCCESS = 'UPDATE_MACHINE_TYPE_SUCCESS';
export const UPDATE_MACHINE_TYPE_FAIL = 'UPDATE_MACHINE_TYPE_FAIL';

export const DELETE_MACHINE_TYPE_REQUEST = 'DELETE_MACHINE_TYPE_REQUEST';
export const DELETE_MACHINE_TYPE_SUCCESS = 'DELETE_MACHINE_TYPE_SUCCESS';
export const DELETE_MACHINE_TYPE_FAIL = 'DELETE_MACHINE_TYPE_FAIL';